"""
Django settings for weddingwebsite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-csan(adwbl9y!**1t#bk4ykc8c190yij9l-8hfx+igl9oubc32'
SECRET_KEY = os.environ.get('SECRET_KEY', SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allow hosts from env (comma-separated), default to '*'
# Normalize entries to support values like 'https://example.com' or 'example.com:443'
_def_allowed = os.environ.get('ALLOWED_HOSTS', '*')

def _parse_allowed_hosts(value: str):
    hosts = []
    for h in [x.strip() for x in value.split(',')]:
        if not h:
            continue
        if h == '*':
            return ['*']
        # Strip scheme if present
        if '://' in h:
            h = h.split('://', 1)[1]
        # Remove path, query, fragment
        h = h.split('/', 1)[0]
        h = h.split('?', 1)[0]
        h = h.split('#', 1)[0]
        # Strip port if present
        h = h.split(':', 1)[0]
        hosts.append(h.lower())
    # Deduplicate preserving order; fall back to wildcard if empty
    return list(dict.fromkeys(hosts)) or ['*']

ALLOWED_HOSTS = _parse_allowed_hosts(_def_allowed)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invitation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Honor X-Forwarded-Proto headers set by Heroku's router
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Redirect HTTP to HTTPS in production
if not DEBUG:
    SECURE_SSL_REDIRECT = True

# CSRF trusted origins for Heroku; comma-separated list in env
_raw_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.herokuapp.com')
CSRF_TRUSTED_ORIGINS = []
for _origin in [h.strip() for h in _raw_csrf_origins.split(',') if h.strip()]:
    # If origin lacks a scheme, default to https://
    if '://' not in _origin:
        _origin = f'https://{_origin}'
    CSRF_TRUSTED_ORIGINS.append(_origin)
# Deduplicate while preserving order
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

ROOT_URLCONF = 'weddingwebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weddingwebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_url = os.environ.get('DATABASE_URL')
_ssl_required = False
if _db_url and _db_url.startswith(('postgres://', 'postgresql://')):
    # Require SSL on hosted Postgres unless explicitly disabled
    _ssl_required = (os.environ.get('DISABLE_DB_SSL', 'False') != 'True')

if _db_url:
    DATABASES = {
        'default': dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            ssl_require=_ssl_required,
        )
    }
else:
    # Local default: SQLite without SSL options
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True

USE_TZ = True

# Add language settings
LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '简体中文'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
# Important: don't include app static folders in STATICFILES_DIRS; AppDirectoriesFinder
# already discovers 'static' folders inside installed apps. Including them here causes
# duplicate paths during collectstatic.
_project_static = BASE_DIR / 'static'
STATICFILES_DIRS = [_project_static] if _project_static.exists() else []
# Use default staticfiles storage when DEBUG, otherwise use whitenoise manifest storage
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Reduce slug size by removing un-hashed originals from STATIC_ROOT
    WHITENOISE_KEEP_ONLY_HASHED_FILES = True

# Security hardening in production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@weddingwebsite.com')
NOTIFICATION_EMAIL = os.environ.get('NOTIFICATION_EMAIL', 'joelngzh@gmail.com')
