# Generated by Django 5.2.4 on 2025-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='connected_to',
            field=models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.TextField(),
        ),
    ]
