# Generated by Django 5.2.4 on 2025-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_rsvp_connected_to_alter_rsvp_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='carpark_slot_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='food_allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='other_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='reservation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
