# Generated by Django 5.2.4 on 2025-07-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('usher', 'Usher'), ('photography', 'Photography'), ('videography', 'Videography'), ('worship', 'Worship'), ('setup', 'Setup'), ('teardown', 'Teardown'), ('carpark', 'Carpark'), ('screens', 'Screens'), ('lights', 'Lights'), ('sound', 'Sound')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='roles',
            field=models.ManyToManyField(blank=True, to='invitation.volunteerrole'),
        ),
    ]
