# Generated by Django 5.2.4 on 2025-07-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_volunteerrole_volunteer_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
