# Generated by Django 5.2.4 on 2025-07-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_volunteer_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='role_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
