# Generated by Django 5.2.4 on 2025-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_volunteer_role_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='message',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
