# Generated by Django 5.2.4 on 2025-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_rename_message_volunteer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='connected_to',
            field=models.CharField(choices=[('bride', 'Amanda'), ('groom', 'Joel'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('none', 'No preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('nut_free', 'Nut-Free'), ('no_beef', 'No Beef'), ('other', 'Other (please specify in comments)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='food_allergies',
            field=models.CharField(blank=True, choices=[('none', 'No allergies'), ('peanuts', 'Peanuts'), ('tree_nuts', 'Tree Nuts'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('shellfish', 'Shellfish'), ('wheat', 'Wheat'), ('soy', 'Soy'), ('sesame', 'Sesame'), ('other', 'Other (please specify in comments)')], max_length=255, null=True),
        ),
    ]
