# Generated by Django 5.2.4 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_alter_rsvp_connected_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('none', 'No preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('non_seafood', 'Non-seafood'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('nut_free', 'Nut-Free'), ('no_beef', 'No Beef'), ('other', 'Other (please specify in comments)')], max_length=255, null=True),
        ),
    ]
