# Generated by Django 5.2.4 on 2025-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0011_alter_rsvp_dietary_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('dairy_free', 'Dairy-Free'), ('gluten_free', 'Gluten-Free'), ('halal', 'Halal'), ('no_beef', 'No Beef'), ('no_seafood', 'No seafood'), ('none', 'No preference'), ('nut_free', 'Nut-Free'), ('other', 'Other (please specify in comments)'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='food_allergies',
            field=models.CharField(blank=True, choices=[('dairy_free', 'Dairy-Free'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('milk', 'Milk'), ('none', 'No allergies'), ('other', 'Other (please specify in comments)'), ('peanuts', 'Peanuts'), ('sesame', 'Sesame'), ('shellfish', 'Shellfish'), ('soy', 'Soy'), ('tree_nuts', 'Tree Nuts'), ('wheat', 'Wheat')], max_length=255, null=True),
        ),
    ]
