# Generated by Django 5.2.4 on 2025-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0012_alter_rsvp_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attending',
            field=models.BooleanField(verbose_name='Attending'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Car Plate Number'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='carpark_slot_reservation',
            field=models.BooleanField(default=False, verbose_name='Carpark Slot Reservation'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='connected_to',
            field=models.CharField(choices=[('bride', 'Amanda'), ('groom', 'Joel'), ('both', 'Both')], default='both', max_length=10, verbose_name='Connected to'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('dairy_free', 'Dairy-Free'), ('gluten_free', 'Gluten-Free'), ('halal', 'Halal'), ('no_beef', 'No Beef'), ('no_seafood', 'No seafood'), ('none', 'No preference'), ('nut_free', 'Nut-Free'), ('other', 'Other (please specify in comments)'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], max_length=255, null=True, verbose_name='Dietary Preferences'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='food_allergies',
            field=models.CharField(blank=True, choices=[('dairy_free', 'Dairy-Free'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('milk', 'Milk'), ('none', 'No allergies'), ('other', 'Other (please specify in comments)'), ('peanuts', 'Peanuts'), ('sesame', 'Sesame'), ('shellfish', 'Shellfish'), ('soy', 'Soy'), ('tree_nuts', 'Tree Nuts'), ('wheat', 'Wheat')], max_length=255, null=True, verbose_name='Food Allergies'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='other_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Other Comments'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='reservation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation Reason'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
