# Generated by GitHub Copilot to seed VolunteerRole data on deploy
from django.db import migrations

ROLE_CHOICES = [
    ('usher', 'Usher'),
    ('photography', 'Photography'),
    ('videography', 'Videography'),
    ('worship', 'Worship'),
    ('setup', 'Setup'),
    ('teardown', 'Teardown'),
    ('carpark', 'Carpark'),
    ('screens', 'Screens'),
    ('lights', 'Lights'),
    ('sound', 'Sound'),
]

def seed_roles(apps, schema_editor):
    VolunteerRole = apps.get_model('invitation', 'VolunteerRole')
    for code, _ in ROLE_CHOICES:
        VolunteerRole.objects.get_or_create(name=code)


def unseed_roles(apps, schema_editor):
    # Safe no-op: keep any roles that may have been used
    # If you really need to remove seeded roles, uncomment below.
    # VolunteerRole = apps.get_model('invitation', 'VolunteerRole')
    # VolunteerRole.objects.filter(name__in=[code for code, _ in ROLE_CHOICES]).delete()
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_rsvp_contact_number_alter_rsvp_attending_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_code=unseed_roles),
    ]

