# Generated by Django 5.2.4 on 2025-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0014_populate_volunteer_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
